global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '${ALERTMANAGER_EMAIL_FROM}'
  smtp_auth_username: '${ALERTMANAGER_EMAIL_USER}'
  smtp_auth_password: '${ALERTMANAGER_EMAIL_PASSWORD}'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'critical-notifications'
      continue: true

receivers:
  - name: 'team-notifications'
    email_configs:
      - to: '${ALERTMANAGER_EMAIL_TO}'
        send_resolved: true
    slack_configs:
      - api_url: '${ALERTMANAGER_SLACK_WEBHOOK_URL}'
        channel: '#monitoring'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        actions:
          - type: button
            text: 'Ver no Grafana'
            url: '{{ .CommonAnnotations.grafana_url }}'

  - name: 'critical-notifications'
    email_configs:
      - to: '${ALERTMANAGER_CRITICAL_EMAIL_TO}'
        send_resolved: true
    slack_configs:
      - api_url: '${ALERTMANAGER_SLACK_WEBHOOK_URL}'
        channel: '#critical-alerts'
        send_resolved: true
        title: '🚨 {{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        actions:
          - type: button
            text: 'Ver no Grafana'
            url: '{{ .CommonAnnotations.grafana_url }}'

templates:
  - '/etc/alertmanager/templates/*.tmpl'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'job'] 