global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'vale-cashback-api'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['api:3000']
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: 'vale-cashback-client'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['client:80']
    scrape_interval: 5s
    scrape_timeout: 4s

remote_write:
  - url: "http://remote-write:9201/write"
    remote_timeout: 30s
    queue_config:
      capacity: 2500
      max_shards: 200
      max_samples_per_send: 500
      batch_send_deadline: 5s
      min_shards: 1
      max_retries: 10
      min_backoff: 30ms
      max_backoff: 100ms

remote_read:
  - url: "http://remote-read:9201/read"
    remote_timeout: 1m
    read_recent: true 